# Generated by Django 6.0 on 2025-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='seller/avatar'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='seller/avatar'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='seller/avatar'),
        ),
    ]
