# Generated by Django 6.0 on 2025-12-15 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customerprofile_avatar_sellerprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified', 'is_suspended'], name='account_sel_is_veri_894913_idx'),
        ),
    ]
