# Generated by Django 6.0 on 2025-12-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sellerprofile_account_sel_is_veri_894913_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer/avatar'),
        ),
    ]
