# Generated by Django 6.0 on 2025-12-20 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customerprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerprofile',
            name='account_sel_is_veri_894913_idx',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='suspended_reason',
            new_name='blocked_reason',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='is_suspended',
            new_name='is_blocked',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified', 'is_blocked'], name='account_sel_is_veri_69130c_idx'),
        ),
    ]
