# Generated by Django 6.0 on 2025-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='store/banners'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store/logos'),
        ),
    ]
