# Generated by Django 6.0 on 2025-12-13 22:55

import core.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.user.CustomUserManager()),
            ],
        ),
    ]
