# Generated by Django 6.0 on 2025-12-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'account'), ('model', 'customerprofile')), models.Q(('app_label', 'account'), ('model', 'sellerprofile')), models.Q(('app_label', 'account'), ('model', 'staffprofile')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='address', to='contenttypes.contenttype'),
        ),
    ]
