# Generated by Django 6.0 on 2025-12-20 10:32

import address.models.address
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_options_alter_address_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, validators=[address.models.address.validate_country_code]),
        ),
    ]
